### ISSUE TITLE
Bot down

### ISSUE THREAD

**Issue by worldofmadness** [3ventic/BotVentic#12] opened 2016-09-09 12:49 UTC
Discord did changes it seems bot will not connect no more. Other bot maker sent out patches to coŕrect the issue. Any ideas when a patch will come with this one?

**Comment by 3ventic** [comment] 2016-09-09 13:07
Was fixed in the last commit 5h ago. I'll upload a new release later today. For the time being, adding "bot " to the start of the token in the config should work.

**Comment by worldofmadness** [comment] 2016-09-09 13:09
Ok thank you.

**Comment by 3ventic** [comment] 2016-09-09 18:51
It's there now, forgot to change version number so it's still 1.0

**Comment by worldofmadness** [comment] 2016-09-09 19:04
Hi thanks for the update unfortunately it still will not work see screen shots below of what happens on start up

https://puu.sh/r5wf6/fcac008205.png

**Comment by 3ventic** [comment] 2016-09-09 19:27
It's the same files running on my computer, so I haven't a clue on why it would fail to load the DLL.

**Comment by worldofmadness** [comment] 2016-09-09 19:35
no idea either i tried it on 4 PCs and it does  the same thing noidea as to why it was working before so im at a losss

**Comment by 3ventic** [comment] 2016-09-09 20:49
I know _what_ the problem is, but I don't know _why_ it's happening. The exact same assemblies work fine on my computer, but not on another.

**Comment by worldofmadness** [comment] 2016-09-09 22:50
that doesnt sound good.

let me know if you find the problem :)

**Comment by worldofmadness** [comment] 2016-09-10 21:13
any luck with the issue?

**Comment by worldofmadness** [comment] 2016-09-16 21:51
any luck with the new update for bot release?

**Comment by 3ventic** [comment] 2016-09-17 08:53
I don't currently have the time to figure out why it's referencing the wrong version of json.net even though it's done nowhere in the project, but [the clickonce setup works](https://twitchstuff.3v.fi/botventic/installer/publish.htm).

**Closed as completed by 3ventic** 2016-09-17 08:53 UTC
